repo: 'icons'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-1
  - html
  - modulifier
  - modulifier-list-group
  - modulifier-icons
  - screenshots-320

html:
  - path: 'index.html'
    has:
      - 'ol'
      - 'ol > li'
      - 'span'
      - 'img'
      - '.icon-label'
    search:
      - 'Ankylosaurus'
      - 'Hadrosaur'
      - 'Stegosaurus'
      - 'Triceratops'
